## Numpy Basics <hr style="border:2.5px solid rgba(255, 0, 0, 1)"></hr>

<b>AG D. Evangelista</b><br>
Comptech Student T09

In [5]:
#imports and packages
import numpy as np

In [6]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

In [8]:
np.shape(my_array)

(3,)

## 2D Array <hr style="border:2.5px solid rgba(255, 0, 0, 1)"></hr>

In [11]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])

my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
np.shape(my_array)

(2, 3)

In [13]:
t_array = my_array.T
t_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [15]:
np.shape(t_array)

(3, 2)

## MEASURES OF CENTRAL TENDENCY <hr style="border:2.5px solid rgba(255, 0, 0, 1)"></hr>